<?php

/**
 * BaseSemestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nome
 * @property date $data_inicio
 * @property date $data_proposta
 * @property date $data_apresentacao
 * 
 * @method string   getNome()              Returns the current record's "nome" value
 * @method date     getDataInicio()        Returns the current record's "data_inicio" value
 * @method date     getDataProposta()      Returns the current record's "data_proposta" value
 * @method date     getDataApresentacao()  Returns the current record's "data_apresentacao" value
 * @method Semestre setNome()              Sets the current record's "nome" value
 * @method Semestre setDataInicio()        Sets the current record's "data_inicio" value
 * @method Semestre setDataProposta()      Sets the current record's "data_proposta" value
 * @method Semestre setDataApresentacao()  Sets the current record's "data_apresentacao" value
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSemestre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('semestre');
        $this->hasColumn('nome', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('data_inicio', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_proposta', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_apresentacao', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}