<?php

/**
 * BaseEstudante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property string $telefone
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Projeto
 * 
 * @method integer             getUsuarioId()  Returns the current record's "usuario_id" value
 * @method string              getTelefone()   Returns the current record's "telefone" value
 * @method Usuario             getUsuario()    Returns the current record's "Usuario" value
 * @method Doctrine_Collection getProjeto()    Returns the current record's "Projeto" collection
 * @method Estudante           setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Estudante           setTelefone()   Sets the current record's "telefone" value
 * @method Estudante           setUsuario()    Sets the current record's "Usuario" value
 * @method Estudante           setProjeto()    Sets the current record's "Projeto" collection
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudante');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('telefone', 'string', 14, array(
             'type' => 'string',
             'length' => 14,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Projeto', array(
             'local' => 'id',
             'foreign' => 'estudante_id'));
    }
}