<?php

/**
 * BaseProfessor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property string $instituicao
 * @property string $titulacao
 * @property integer $experiencia
 * @property boolean $substituto
 * @property boolean $comissao
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Projeto
 * 
 * @method integer             getUsuarioId()   Returns the current record's "usuario_id" value
 * @method string              getInstituicao() Returns the current record's "instituicao" value
 * @method string              getTitulacao()   Returns the current record's "titulacao" value
 * @method integer             getExperiencia() Returns the current record's "experiencia" value
 * @method boolean             getSubstituto()  Returns the current record's "substituto" value
 * @method boolean             getComissao()    Returns the current record's "comissao" value
 * @method Usuario             getUsuario()     Returns the current record's "Usuario" value
 * @method Doctrine_Collection getProjeto()     Returns the current record's "Projeto" collection
 * @method Professor           setUsuarioId()   Sets the current record's "usuario_id" value
 * @method Professor           setInstituicao() Sets the current record's "instituicao" value
 * @method Professor           setTitulacao()   Sets the current record's "titulacao" value
 * @method Professor           setExperiencia() Sets the current record's "experiencia" value
 * @method Professor           setSubstituto()  Sets the current record's "substituto" value
 * @method Professor           setComissao()    Sets the current record's "comissao" value
 * @method Professor           setUsuario()     Sets the current record's "Usuario" value
 * @method Professor           setProjeto()     Sets the current record's "Projeto" collection
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfessor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('professor');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             ));
        $this->hasColumn('instituicao', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('titulacao', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('experiencia', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('substituto', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('comissao', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Projeto', array(
             'local' => 'id',
             'foreign' => 'professor_id'));
    }
}