<?php

/**
 * BaseDefesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $projeto_id
 * @property integer $status
 * @property date $data_requisicao
 * @property date $data_feedback_orientador
 * @property date $data_feedback_comissao
 * @property date $data_sugestao
 * @property date $data_autorizacao
 * @property string $documento
 * @property string $documento_final
 * @property integer $qtde_paginas
 * @property Projeto $Projeto
 * @property Doctrine_Collection $Comentarios
 * 
 * @method integer             getProjetoId()                Returns the current record's "projeto_id" value
 * @method integer             getStatus()                   Returns the current record's "status" value
 * @method date                getDataRequisicao()           Returns the current record's "data_requisicao" value
 * @method date                getDataFeedbackOrientador()   Returns the current record's "data_feedback_orientador" value
 * @method date                getDataFeedbackComissao()     Returns the current record's "data_feedback_comissao" value
 * @method date                getDataSugestao()             Returns the current record's "data_sugestao" value
 * @method date                getDataAutorizacao()          Returns the current record's "data_autorizacao" value
 * @method string              getDocumento()                Returns the current record's "documento" value
 * @method string              getDocumentoFinal()           Returns the current record's "documento_final" value
 * @method integer             getQtdePaginas()              Returns the current record's "qtde_paginas" value
 * @method Projeto             getProjeto()                  Returns the current record's "Projeto" value
 * @method Doctrine_Collection getComentarios()              Returns the current record's "Comentarios" collection
 * @method Defesa              setProjetoId()                Sets the current record's "projeto_id" value
 * @method Defesa              setStatus()                   Sets the current record's "status" value
 * @method Defesa              setDataRequisicao()           Sets the current record's "data_requisicao" value
 * @method Defesa              setDataFeedbackOrientador()   Sets the current record's "data_feedback_orientador" value
 * @method Defesa              setDataFeedbackComissao()     Sets the current record's "data_feedback_comissao" value
 * @method Defesa              setDataSugestao()             Sets the current record's "data_sugestao" value
 * @method Defesa              setDataAutorizacao()          Sets the current record's "data_autorizacao" value
 * @method Defesa              setDocumento()                Sets the current record's "documento" value
 * @method Defesa              setDocumentoFinal()           Sets the current record's "documento_final" value
 * @method Defesa              setQtdePaginas()              Sets the current record's "qtde_paginas" value
 * @method Defesa              setProjeto()                  Sets the current record's "Projeto" value
 * @method Defesa              setComentarios()              Sets the current record's "Comentarios" collection
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefesa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('defesa');
        $this->hasColumn('projeto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('data_requisicao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_feedback_orientador', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_feedback_comissao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_sugestao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('data_autorizacao', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('documento', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('documento_final', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('qtde_paginas', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Projeto', array(
             'local' => 'projeto_id',
             'foreign' => 'id'));

        $this->hasMany('Comentario as Comentarios', array(
             'local' => 'id',
             'foreign' => 'defesa_id',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}