<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Estudante $Estudante
 * @property Professor $Professor
 * 
 * @method Estudante getEstudante() Returns the current record's "Estudante" value
 * @method Professor getProfessor() Returns the current record's "Professor" value
 * @method Usuario   setEstudante() Sets the current record's "Estudante" value
 * @method Usuario   setProfessor() Sets the current record's "Professor" value
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfGuardUser
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudante', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('Professor', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}