<?php

/**
 * BaseComentario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $comentario
 * @property boolean $liberado
 * @property integer $professor_id
 * @property integer $proposta_id
 * @property integer $defesa_id
 * @property Professor $Professor
 * @property Proposta $Proposta
 * 
 * @method string     getComentario()   Returns the current record's "comentario" value
 * @method boolean    getLiberado()     Returns the current record's "liberado" value
 * @method integer    getProfessorId()  Returns the current record's "professor_id" value
 * @method integer    getPropostaId()   Returns the current record's "proposta_id" value
 * @method integer    getDefesaId()     Returns the current record's "defesa_id" value
 * @method Professor  getProfessor()    Returns the current record's "Professor" value
 * @method Proposta   getProposta()     Returns the current record's "Proposta" value
 * @method Comentario setComentario()   Sets the current record's "comentario" value
 * @method Comentario setLiberado()     Sets the current record's "liberado" value
 * @method Comentario setProfessorId()  Sets the current record's "professor_id" value
 * @method Comentario setPropostaId()   Sets the current record's "proposta_id" value
 * @method Comentario setDefesaId()     Sets the current record's "defesa_id" value
 * @method Comentario setProfessor()    Sets the current record's "Professor" value
 * @method Comentario setProposta()     Sets the current record's "Proposta" value
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComentario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comentario');
        $this->hasColumn('comentario', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('liberado', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('professor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('proposta_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('defesa_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Professor', array(
             'local' => 'professor_id',
             'foreign' => 'id'));

        $this->hasOne('Proposta', array(
             'local' => 'proposta_id',
             'foreign' => 'id'));
    }
}