<?php

/**
 * ComentarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComentarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComentarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comentario');
    }

    public function alreadyExists(Proposta $proposta, Professor $professor){
      $numComments = $this->createQuery('c')
              ->where('c.professor_id = ?', $professor->getId())
              ->andWhere('c.proposta_id = ?', $proposta->getId())
              ->count();

      return $numComments > 0;
    }

}