<?php

/**
 * Defesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Defesa extends BaseDefesa
{
  const NAO_ANALISADO = 200;
  const APROVADO      = 201;
  const REPROVADO     = 202;
  const LIBERADO      = 203;
  const NAO_LIBERADO  = 204;
  const DEFENDIDO     = 205;

  static $status = array(
      self::NAO_ANALISADO => "Defesa não analisada",
      self::APROVADO => "Defesa aprovada pelo orientador",
      self::REPROVADO => "Defesa reprovada pelo orientador",
      self::LIBERADO => "Defesa aprovada pela comissão",
      self::NAO_LIBERADO => "Defesa reprovada pela comissão",
      self::DEFENDIDO => "Projeto defendido"
  );

    protected $positiveComments;
    protected $negativeComments;
    protected $positivePercentage;
    protected $negativePercentage;
    protected $countComissao;

    public function audit(Professor $professor, $approved, $comment){
      $this->addComment($professor, $approved, $comment);

      if($this->canBeAudited()){
        $positiveDecision = $this->positivePercentage >= $this->negativePercentage;

        $status = $positiveDecision ? Defesa::LIBERADO : Defesa::NAO_LIBERADO;
        $this->setStatus($status);
        $this->save();
      }
    }

    protected function addComment(Professor $professor, $approved, $text){
      $alreadyAuditedByThisProfessor = ComentarioTable::getInstance()->alreadyExistsOnDefesa($this, $professor);
      if(!$alreadyAuditedByThisProfessor){
        $comment = new Comentario();
        $comment->setProfessor($professor);
        $comment->setDefesa($this);
        $comment->setComentario($text);
        $comment->setLiberado($approved);
        $comment->save();
      }
    }

    protected function canBeAudited(){
      $this->calculatePercentages();
      $quorum = $this->countComissao / 2;
      $qtyComments = $this->positiveComments + $this->negativeComments;

      return ($qtyComments == $this->countComissao) || ($this->positivePercentage >= $quorum) || ($this->negativePercentage > $quorum);
    }

    protected function calculatePercentages(){
      $this->loadComments();
      $this->countComissao = ProfessorTable::getInstance()->countComissao();

      $this->positivePercentage = 0;
      $this->negativePercentage = 0;

      if($this->countComissao > 0){
        $this->positivePercentage = $this->positiveComments / $this->countComissao;
        $this->negativePercentage = $this->negativeComments / $this->countComissao;
      }
    }

    protected function loadComments(){
      $comments = $this->getComentarios();
      $this->positiveComments = 0;
      $this->negativeComments = 0;
      foreach($comments as $c){
        if($c->getLiberado()){
          $this->positiveComments++;
        }else{
          $this->negativeComments++;
        }
      }
    }

    public function isDelayed($now){
      extract(Semestre::getTimestamps($this->getProjeto()));
      if($now == null){
        $now = time();
      }
      return ($now > $dataDefesa);
    }

    public function responsibleForDelay($now = null){
      if($now == null){
        $now = time();
      }

      if($this->isDelayed($now)){
        if($this->getStatus() == self::NAO_ANALISADO){
          return Usuario::PROFESSOR;
        }else if($this->getStatus() == self::APROVADO){
          return Usuario::COMISSAO;
        }
      }

      return '';
    }
}
