<?php

/**
 * Defesa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Defesa extends BaseDefesa
{
  const NAO_ANALISADO = 0;
  const APROVADO = 1;
  const REPROVADO = 2;
  const LIBERADO = 3;
  const NAO_LIBERADO = 4;

  static $status = array(
      self::NAO_ANALISADO => "Defesa não analisada",
      self::APROVADO => "Defesa aprovada pelo orientador",
      self::REPROVADO => "Defesa reprovada pelo orientador",
      self::LIBERADO => "Defesa aprovada pela comissão",
      self::NAO_LIBERADO => "Defesa reprovada pela comissão"
  );

}
