<?php

/**
 * DefesaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefesaTable extends Doctrine_Table
{

  public function construct(){
    $this->addNamedQuery('find.all.visible.by.professor',
      $this->createQuery('d')
           ->select('d.*')
           ->where('d.documento is not null')
           ->andWhere("d.documento != ''")
    );

    $this->addNamedQuery('find.all.visible.by.comission',
      $this->createQuery('d')
           ->select('d.*')
           ->whereIn('d.status', array(Defesa::LIBERADO, Defesa::APROVADO, Defesa::NAO_LIBERADO, Defesa::DEFENDIDO))
    );

  }
  
    /**
     * Returns an instance of this class.
     *
     * @return object DefesaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Defesa');
    }
}