<?php

/**
 * EstudanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstudanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstudanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estudante');
    }
}