<?php

/**
 * ProfessorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfessorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfessorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Professor');
    }
}