<?php

/**
 * ProfessorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfessorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfessorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Professor');
    }

    public function findEmailsComissao(){
      $query = $this->createQuery('p')
              ->select('u.email_address as email_address')
              ->innerJoin('p.Usuario u')
              ->where('p.is_comissao = ?', true);

      $emails = $query->execute(array(), Doctrine_Core::HYDRATE_SCALAR);
      $arrEmails = array();
      foreach($emails as $email){
        $arrEmails[] = $email['u_email_address'];
      }

      return $arrEmails;
    }

    public function countComissao(){
      $count = $this->createQuery('p')
              ->where('p.is_comissao = ?', true)
              ->count();
      return $count;
    }

 }