<?php

/**
 * Projeto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projeto extends BaseProjeto
{
  public function hasProposta(){
    $proposta = $this->getProposta();
    return ($proposta != null && $proposta->exists());
  }

  public function hasDefesa(){
    $defesa = $this->getDefesa();
    return ($defesa != null && $defesa->exists());
  }

  public function hasPropostaWithAttachedFile(){
    if($this->hasProposta()){
      $proposta = $this->getProposta();
      return file_exists($proposta->getDocumento());
    }
    return false;
  }

  public function delete(Doctrine_Connection $conn = null){
    if($this->hasPropostaWithAttachedFile()){
      unlink($this->getProposta()->getDocumento());
    }
    parent::delete($conn);
  }

  public function getStatus(){
    if($this->hasPropostaWithAttachedFile()){
      return Proposta::$status[$this->getProposta()->getStatus()];
    }else{
      return "Proposta pendente";
    }
  }

  public function mayRequestPresentation(){
    if($this->hasPropostaWithAttachedFile()){
      return $this->getProposta()->getStatus() == Proposta::LIBERADO;
    }

    return false;
  }

}
