<?php

/**
 * Projeto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Projeto extends BaseProjeto
{
  public function hasProposta(){
    $proposta = $this->getProposta();
    return ($proposta != null && $proposta->exists());
  }

  public function hasPropostaWithAttachedFile(){
    if($this->hasProposta()){
      return file_exists($this->getProposta()->getDocumento());
    }
    return false;
  }
}
