<?php

/**
 * Proposta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Proposta extends BaseProposta
{
    const NAO_ANALISADO = 0;
    const APROVADO = 1;
    const REPROVADO = 2;
    const LIBERADO = 3;
    const NAO_LIBERADO = 4;

    static $status = array(
        self::NAO_ANALISADO => "Não analisada",
        self::APROVADO => "Aprovado pelo orientador",
        self::REPROVADO => "Reprovado pelo orientador",
        self::LIBERADO => "Aprovado pela comissão",
        self::NAO_LIBERADO => "Reprovado pela comissão"
    );
}
