<?php

/**
 * PropostaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropostaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropostaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proposta');
    }
}