<?php

/**
 * PropostaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropostaTable extends Doctrine_Table
{

  public function construct(){
    $this->addNamedQuery('find.all.visible.by.professor',
      $this->createQuery('p')
           ->select('p.*')
           ->where('p.documento is not null')
           ->andWhere("p.documento != ''")
           ->andWhere('p.Projeto.professor_id = :professor_id')
    );

    $this->addNamedQuery('find.all.visible.by.comission',
      $this->createQuery('p')
           ->select('p.*')
           ->whereIn('p.status', array(Proposta::LIBERADO, Proposta::APROVADO, Proposta::NAO_LIBERADO))
    );

  }

    /**
     * Returns an instance of this class.
     *
     * @return object PropostaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proposta');
    }
}