<?php

/**
 * Semestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Semestre extends BaseSemestre
{
  const COLACAO_NORMAL = 1;
  const COLACAO_ESPECIAL = 2;

  static $tiposColacao = array(
      self::COLACAO_NORMAL => "Colação normal",
      self::COLACAO_ESPECIAL => "Colação especial"
  );

  public function __toString(){
    return $this->getNome();
  }
}
