<?php

/**
 * Semestre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    monomanager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Semestre extends BaseSemestre
{
  const COLACAO_NORMAL = 1;
  const COLACAO_ESPECIAL = 2;

  static $tiposColacao = array(
      self::COLACAO_NORMAL => "Colação normal",
      self::COLACAO_ESPECIAL => "Colação especial"
  );

  public function __toString(){
    return $this->getNome();
  }

  public static function getTimestamps(Projeto $projeto){
    $semestre = $projeto->getSemestre();
    $tipoColacao = $projeto->getTipoColacao();

    if($tipoColacao == self::COLACAO_NORMAL){
      $dataProposta = $semestre->getDataMaxProposta();
      $dataCopiao = $semestre->getDataMaxProposta();
      $dataDefesa = $semestre->getDataMaxDefesa();
      $dataColacao = $semestre->getDataColacao();
    }else{
      $dataProposta = $semestre->getDataMaxPropostaEspecial();
      $dataCopiao = $semestre->getDataMaxPropostaEspecial();
      $dataDefesa = $semestre->getDataMaxDefesaEspecial();
      $dataColacao = $semestre->getDataColacaoEspecial();
    }

    $dataProposta = Util::DBDateToTimestamp($dataProposta);
    $dataCopiao = Util::DBDateToTimestamp($dataCopiao);
    $dataDefesa = Util::DBDateToTimestamp($dataDefesa);
    $dataColacao = Util::DBDateToTimestamp($dataColacao);

    $timestamps = array(
        'dataProposta' => $dataProposta,
        'dataCopiao' => $dataCopiao,
        'dataDefesa' => $dataDefesa,
        'dataColacao' => $dataColacao
    );

    return $timestamps;
  }
}
