<?php

/**
 * SemestreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SemestreTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object SemestreTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Semestre');
  }

  public function findEarliestYearOrDefault($default){
    $query = $this->createQuery()->select("min(to_char(data_max_proposta, 'YYYY')) as minYear")->fetchOne();
    $minYear = $query['minYear'];

    if(empty($minYear)){
      $minYear = $default;
    }

    return $minYear;
  }
}