# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

proposta:
  url: /projeto/:projeto_id/proposta
  param: {module: proposta, action: index}

proposta_avaliar:
  url: /projeto/:projeto_id/proposta/aprovar/:aprovado
  param: {module: proposta, action: aprovar}
  requirements:
    aprovado: (true|false)

proposta_liberar:
  url: /projeto/:projeto_id/proposta/liberar/:liberado
  param: {module: proposta, action: liberar}
  requirements:
    liberado: (true|false)

download_documento:
  url: /projeto/:projeto_id/proposta/download
  param: {module: proposta, action: download}

download_copiao:
  url: /projeto/:projeto_id/defesa/download
  param: {module: defesa, action: download}

defesa:
  url: /projeto/:projeto_id/defesa
  param: {module: defesa, action: index}

defesa_avaliar:
  url: /projeto/:projeto_id/defesa/aprovar/:aprovado
  param: {module: defesa, action: aprovar}
  requirements:
    aprovado: (true|false)

defesa_liberar:
  url: /projeto/:projeto_id/defesa/liberar/:liberado
  param: {module: defesa, action: liberar}
  requirements:
    liberado: (true|false)

defesa_concluir:
  url: /projeto/:projeto_id/defesa/concluir/:concluido
  param: {module: defesa, action: concluir}
  requirements:
    concluido: (true|false)

documento_final:
	url: /projeto/:projeto_id
	param: {module: defesa, action: documentofinal}

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

