Usuario:
  inheritance:
    extends: sfGuardUser
    type: simple

Estudante:
  columns:
    id:
      primary: true
      type: integer
    telefone:
      type: string(14)
  relations:
    Usuario:
      local: id
      type: one
      foreignType: one
      cascade: [delete]

Professor:
  columns:
    id:
      primary: true
      type: integer
    instituicao:
      type: string(255)
      notnull: true
    titulacao:
      type: string(255)
      notnull: true
    experiencia:
      type: string(30)
    is_substituto:
      type: boolean
    is_comissao:
      type: boolean
  relations:
    Usuario:
      local: id
      type: one
      foreignType: one
      cascade: [delete]

Projeto:
  columns:
    titulo:
      type: string(255)
      notnull: true
    estudante_id:
      type: integer
      notnull: true
    professor_id:
      type: integer
      notnull: true
    coorientadores:
      type: string(255)
    tipo_colacao:
      type: integer(1)
  relations:
    Estudante:
      local: estudante_id
      type: one
      foreignType: many
    Professor:
      local: professor_id
      type: one
      foreignType: many
    Proposta:
      local: id
      foreign: projeto_id
      type: one
      cascade: [delete]
    Defesa:
      local: id
      foreign: projeto_id
      type: one
      cascade: [delete]

Proposta:
  columns:
    projeto_id:
      type: integer
      notnull: true
    status:
      type: integer(1)
    data_submissao:
      type: date
    data_feedback_orientador:
      type: date
    data_feedback_comissao:
      type: date
    documento:
      type: string(255)
  relations:
    Projeto:
      local: projeto_id
      type: one
    Comentarios:
      class: Comentario
      local: id
      foreign: proposta_id
      type: many
      cascade: [delete]

Semestre:
  columns:
    nome:
      type: string(30)
    data_colacao:
      type: date
    data_max_proposta:
      type: date
    data_max_copiao:
      type: date
    data_max_defesa:
      type: date
    data_colacao_especial:
      type: date
    data_max_proposta_especial:
      type: date
    data_max_copiao_especial:
      type: date
    data_max_defesa_especial:
      type: date

Comentario:
  columns:
    comentario:
      type: string
    liberado:
      type: boolean
      notnull: true
    professor_id:
      type: integer
      notnull: true
    proposta_id:
      type: integer
    defesa_id:
      type: integer
  relations:
    Professor:
      local: professor_id
      type: one
      foreignType: many
    Proposta:
      local: proposta_id
      type: one
      foreignType: many
    Defesa:
      local: defesa_id
      type: one
      foreignType: many

Defesa:
  columns:
    projeto_id:
      type: integer
      notnull: true
    status:
      type: integer(1)
    data_requisicao:
      type: date
    data_feedback_orientador:
      type: date
    data_feedback_comissao:
      type: date
    data_sugestao:
      type: date
    data_autorizacao:
      type: date
    documento:
      type: string(255)
    documento_final:
      type: string(255)
    qtde_paginas:
      type: integer
  relations:
    Projeto:
      local: projeto_id
      type: one
    Comentarios:
      class: Comentario
      local: id
      foreign: defesa_id
      type: many
      cascade: [delete]
