Usuario:
  inheritance:
    extends: sfGuardUser
    type: simple

Estudante:
  columns:
    id:
      primary: true
      type: integer
    telefone:
      type: string(14)
  relations:
    Usuario:
      local: id
      type: one
      foreignType: one
      cascade: [delete]

Professor:
  columns:
    id:
      primary: true
      type: integer
    instituicao:
      type: string(255)
      notnull: true
    titulacao:
      type: string(255)
      notnull: true
    experiencia:
      type: string(30)
    is_substituto:
      type: boolean
    is_comissao:
      type: boolean
  relations:
    Usuario:
      local: id
      type: one
      foreignType: one
      cascade: [delete]

Projeto:
  columns:
    titulo:
      type: string(255)
      notnull: true
    estudante_id:
      type: integer
      notnull: true
    professor_id:
      type: integer
      notnull: true
    coorientadores:
      type: string(255)
    data_requisicao:
      type: date
    data_sugestao:
      type: date
    data_aprovacao:
      type: date
    data_autorizacao:
      type: date
    documento:
      type: string(255)
    documento_final:
      type: string(255)
    qtde_linhas:
      type: integer
  relations:
    Estudante:
      local: estudante_id
      type: one
      foreignType: many
    Professor:
      local: professor_id
      type: one
      foreignType: many
    Proposta:
      local: id
      foreign: projeto_id
      type: one
      cascade: [delete]

Proposta:
  columns:
    projeto_id:
      type: integer
      notnull: true
    status:
      type: integer(1)
    comentarios:
      type: string
    data_submissao:
      type: date
    data_feedback:
      type: date
    documento:
      type: string(255)
  relations:
    Projeto:
      local: projeto_id
      type: one

Semestre:
  columns:
    nome:
      type: string(30)
    data_inicio:
      type: date
    data_proposta:
      type: date
    data_apresentacao:
      type: date