Usuario:
  tableName: USUARIOS
  columns:
    id:
      name: id
      type: integer(4)
      primary: true
      sequence: squsuario
    login:
      name: login
      type: string
    email:
      name: email
      type: string

Estudante:
  tableName: ESTUDANTES
  columns:
    usuario_id: usuario_id
    type: integer(4)
  relations:
    usuario:


Professor:
  tableName: PROFESSORES
  columns:
